version: "3.7"

services:
  my-backend:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./index.js:/myfolder/index.js
      - ./email.js:/myfolder/email.js
      - ./phone.js:/myfolder/phone.js
      - ./models/user.model.js:/myfolder/user.model.js
      - ./personal.js:/myfolder/personal.js
      - ./scraping.js:/myfolder/scraping.js
    ports:
      - 3000:3000
  my-database:
    image: mongo:5
    ports:
      - 27017:27017
