version: "3.7"

# 컴퓨터들(s)

services:
  # 컴퓨터 이름
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000

  # 컴퓨터 이름
  my-databaes:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - 27017:27017
